events {}

http {
  upstream menu_service {
    server svc-menu:8081;
  }

  upstream orders_service {
    server svc-orders:8082;
  }

  server {
    listen 8080;

    location /api/menu/ {
      proxy_pass http://menu_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/orders {
      proxy_pass http://orders_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
